
<?php
/** ONE-TIME BOOTSTRAP — visit /public/setup.php once, then DELETE this file. */
require_once __DIR__ . '/../config/database.php';
$log = [];
try {

// ---------- 1. TABLES (idempotent) ----------
$pdo->exec("CREATE TABLE IF NOT EXISTS users (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL, role VARCHAR(50) DEFAULT 'customer',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW())");
$pdo->exec("CREATE TABLE IF NOT EXISTS subscriptions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES users(id) ON DELETE CASCADE,
 plan VARCHAR(100), status VARCHAR(50) DEFAULT 'active_trial',
 price DECIMAL(10,2) DEFAULT 0,
 trial_ends_at TIMESTAMP WITH TIME ZONE, period_ends_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW())");
$pdo->exec("CREATE TABLE IF NOT EXISTS transactions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES users(id) ON DELETE CASCADE,
 amount DECIMAL(10,2) NOT NULL, method VARCHAR(50), status VARCHAR(50) DEFAULT 'succeeded',
 description TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW())");
$pdo->exec("CREATE TABLE IF NOT EXISTS facilities (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name VARCHAR(255) NOT NULL, type VARCHAR(50), rate DECIMAL(10,2) NOT NULL,
 open_hour INT, close_hour INT, interval_min INT DEFAULT 60, active BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW())");
$pdo->exec("CREATE TABLE IF NOT EXISTS bookings (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 facility_id UUID REFERENCES facilities(id) ON DELETE CASCADE,
 user_id UUID REFERENCES users(id) ON DELETE CASCADE,
 booking_date DATE NOT NULL, slot VARCHAR(50) NOT NULL,
 status VARCHAR(50) DEFAULT 'pending', amount DECIMAL(10,2) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW())");
$log[] = "Tables verified";

// ---------- 2. ADMIN with PHP-generated bcrypt hash ----------
$hash = password_hash('password', PASSWORD_BCRYPT);
$chk = $pdo->prepare("SELECT id FROM users WHERE LOWER(email) = ?");
$chk->execute(['admin@azkejora.io']);
if ($chk->fetch()) {
    $pdo->prepare("UPDATE users SET password_hash = ?, role = 'admin', name = 'Admin User' WHERE LOWER(email) = ?")
        ->execute([$hash, 'admin@azkejora.io']);
    $log[] = "Admin found → password hash regenerated by PHP";
} else {
    $pdo->prepare("INSERT INTO users (name,email,password_hash,role) VALUES (?,?,?,?)")
        ->execute(['Admin User','admin@azkejora.io',$hash,'admin']);
    $log[] = "Admin created";
}

// ---------- 3. DEMO DATA (only if missing) ----------
if ((int)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn() <= 1) {
    $demo = [ // name, email, plan, status, price, trial_hours, period_days
        ['Daniel Wong','daniel@luminares.co','Growth','active',210,null,52],
        ['Nurul Izzah','nurul@kedairakyat.my','Starter','active',90,null,20],
        ['Marcus Teo','marcus@fitzone.asia','Scale','active',450,null,74],
        ['Priya Nair','priya@bloomscafe.com','Starter','active',90,null,8],
        ['Hafiz Rahman','hafiz@servispro.my','Growth','past_due',210,null,-2],
        ['Elena Cruz','elena@studiocrux.co','Scale','canceled',450,null,-40],
        ['Amirul Fikri','amirul@tanjungsports.my',null,'active_trial',0,2,null],
        ['Grace Lim','grace@petalworks.sg',null,'active_trial',0,2,null],
        ['Ryan Ong','ryan@quicklane.io','Starter','canceled',90,null,-70],
    ];
    $insU = $pdo->prepare("INSERT INTO users (name,email,password_hash,role) VALUES (?,?,?,?) RETURNING id");
    $insS = $pdo->prepare("INSERT INTO subscriptions (user_id,plan,status,price,trial_ends_at,period_ends_at) VALUES (?,?,?,?,?,?)");
    $insT = $pdo->prepare("INSERT INTO transactions (user_id,amount,method,status,description) VALUES (?,?,?,?,?)");
    $ids = [];
    foreach ($demo as $d) {
        $insU->execute([$d[0],$d[1],$hash,'customer']); $ids[$d[1]] = $insU->fetchColumn();
        $trial = $d[5] ? date('Y-m-d H:i:s', strtotime("+$d[5] hours")) : null;
        $period = $d[6] !== null ? date('Y-m-d H:i:s', strtotime("+$d[6] days")) : null;
        $insS->execute([$ids[$d[1]],$d[2],$d[3],$d[4],$trial,$period]);
        $insT->execute([$ids[$d[1]], $d[4], $d[4]>0?'Stripe':'None', $d[4]>0?'succeeded':'pending',
            $d[4]>0 ? $d[2].' — 3-month cycle' : 'Trial signup']);
    }
    $log[] = "9 demo customers + subscriptions + transactions seeded";
}

// Safety net: any user without a subscription gets a 2-hour trial
$pdo->exec("INSERT INTO subscriptions (user_id, plan, status, price, trial_ends_at)
 SELECT id, NULL, 'active_trial', 0, NOW() + INTERVAL '2 hours' FROM users u
 WHERE NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.user_id = u.id)");

// Facilities + bookings if empty
if ((int)$pdo->query("SELECT COUNT(*) FROM facilities")->fetchColumn() === 0) {
    $facs = [['Badminton Court 1','court',18],['Glass Meeting Suite','room',45],['The Pavilion Hall','hall',220],
            ['Tennis Court A','court',25],['Board Room B','room',50],['Conference Hall 2','hall',250],
            ['Squash Court 1','court',20],['Yoga Studio','room',35],['Event Space C','hall',300],['Pod Room 1','room',40]];
    $insF = $pdo->prepare("INSERT INTO facilities (name,type,rate,open_hour,close_hour,interval_min,active) VALUES (?,?,?,8,22,60,TRUE) RETURNING id");
    $emails = array_column($demo,1); $i = 0;
    $insB = $pdo->prepare("INSERT INTO bookings (facility_id,user_id,booking_date,slot,status,amount) VALUES (?,?,CURRENT_DATE,?,'confirmed',?)");
    foreach ($facs as $f) {
        $insF->execute($f); $fid = $insF->fetchColumn();
        if (isset($ids[$emails[$i]])) $insB->execute([$fid, $ids[$emails[$i]], ($i+8).':00', $f[2]]);
        $i++;
    }
    $log[] = "10 facilities + bookings seeded";
}

$log[] = "DONE — you can now sign in.";
} catch (Throwable $e) { $log[] = "ERROR: " . $e->getMessage(); }
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Setup</title>
<style>body{font-family:system-ui;background:#F6F7FB;padding:60px;color:#131327}
.card{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;padding:32px;box-shadow:0 12px 32px -16px rgba(19,19,39,.2)}
li{margin:8px 0;font-size:14px}code{background:#f1f5f9;padding:2px 6px;border-radius:4px}</style></head>
<body><div class="card"><h2>⚡ AZ Kejora Bootstrap</h2><ul>
<?php foreach ($log as $l) echo "<li>✔ ".htmlspecialchars($l)."</li>"; ?>
</ul>
<p style="font-size:13px;color:#64748b">Login: <code>admin@azkejora.io</code> / <code>password</code><br>
<b style="color:#e11d48">DELETE setup.php from your server now.</b></p>
<a href="index.php" style="color:#5457e5;font-weight:700">→ Go to login</a>
</div></body></html>
